# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webappName:
  resourceGroup:


stages:
  - stage: build
    jobs:
      - job: build
        steps:
        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'

        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        
        - task: VSTest@2
          inputs:
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)'
            artifact: 'drop'
            publishLocation: 'pipeline'

  - stage: deploy_to_cloud
    jobs:
      - job: deploytoappService
        displayName: 'Deploying to app service'
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'drop'
            targetPath: '$(Pipeline.Workspace)'
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Azure Personal(3772de55-f369-4548-afb2-3811c07a435b)'
            ScriptType: 'InlineScript'
            Inline: |
              <# This sample script creates a web app in App Service with its related resources, and 
              then deploys your web app code from a public GitHub repository (without continuous deployment)
              #>
              
              #$gitrepo = "https://github.com/ajaygupta711/app-service-web-dotnet-get-started.git"
              $webappname = "ajaywebapp$(Get-Random)"
              $location = "Central India"
              $resourceGroup = "ajaysrggroup"
              
              #create resource group
              New-AzResourceGroup -Name $resourceGroup  -Location $location
              
              
              # Create an App Service plan in Free tier.
              New-AzAppServicePlan -Name  $webappname -ResourceGroupName $resourceGroup -Location $location -Tier Free
              
              
              # Create a web app
              New-AzWebApp -Name $webappname -AppServicePlan $webappname -ResourceGroupName $resourceGroup -Location $location
              
              "##vso[task.setvariable variable=resourceGroup;]$resourceGroup"
              "##vso[task.setvariable variable=webappname;]$webappname"
              write-host my resource $(resourceGroup)
              write-host my webappname '$(webappname)'
            azurePowerShellVersion: 'LatestVersion'
        - task: AzureWebApp@1
          enabled: false
          inputs:
            azureSubscription: 'Azure Personal(3772de55-f369-4548-afb2-3811c07a435b)'
            appType: 'webApp'
            appName: '$(webappname)'
            package: '$(Pipeline.Workspace)/**/*.zip'
        - task: AzureRmWebAppDeployment@4
          enabled: false
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Azure Personal(3772de55-f369-4548-afb2-3811c07a435b)'
            appType: 'webApp'
            WebAppName: '$(webappname)'
            packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
        - task: AzurePowerShell@5
          enabled: false
          inputs:
            azureSubscription: 'Azure Personal(3772de55-f369-4548-afb2-3811c07a435b)'
            ScriptType: 'InlineScript'
            Inline: |
              write-host my resource $(resourceGroup)
              write-host my webappname $(webappname)
              write-host package path $(Build.Repository.LocalPath)
              $repol = $(Build.SourcesDirectory)
              write-host package path $(Pipeline.Workspace)
              cd $repol\aspnet-get-started\obj\Release\Package\PackageTmp
              dir
              Compress-Archive -Path * -DestinationPath aspnet-get-started.zip
              $app = Get-AzWebApp -ResourceGroupName $env:resourceGroup -Name $env:webappname
              Publish-AzWebApp -WebApp $app -ArchivePath (Get-Item .\aspnet-get-started.zip).FullName -Force
            azurePowerShellVersion: 'LatestVersion'
        - task: AzurePowerShell@5
          enabled: true
          inputs:
            azureSubscription: 'Azure Personal(3772de55-f369-4548-afb2-3811c07a435b)'
            ScriptType: 'InlineScript'
            Inline: |
              write-host my resource $(resourceGroup)
              write-host my webappname $(webappname)
              write-host package path $(Build.Repository.LocalPath)
              $gitrepo="https://github.com/ajaygupta711/app-service-web-dotnet-get-started.git"
              # Configure GitHub deployment from your GitHub repo and deploy once.
              $PropertiesObject = @{
                  repoUrl = "$gitrepo";
                  branch = "master";
                  isManualIntegration = "true";
              }
              Set-AzResource -Properties $PropertiesObject -ResourceGroupName $(resourceGroup) -ResourceType Microsoft.Web/sites/sourcecontrols -ResourceName $(webappname)/web -ApiVersion 2015-08-01 -Force
            azurePowerShellVersion: 'LatestVersion'
