# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webappName:
  resourceGroup:


stages:
  - stage: build
    jobs:
      - job: build
        steps:
        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'

        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        
        - task: VSTest@2
          inputs:
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
  - stage: deploy_to_cloud
    jobs:
      - job: deploytoappService
        displayName: 'Deploying to app service'
        steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Azure Personal(3772de55-f369-4548-afb2-3811c07a435b)'
            ScriptType: 'InlineScript'
            Inline: |
              <# This sample script creates a web app in App Service with its related resources, and 
              then deploys your web app code from a public GitHub repository (without continuous deployment)
              #>
              
              #$gitrepo = "https://github.com/ajaygupta711/app-service-web-dotnet-get-started.git"
              $webappname = "ajaywebapp$(Get-Random)"
              $location = "Central India"
              $resourceGroup = "ajaysrggroup"
              
              #create resource group
              New-AzResourceGroup -Name $resourceGroup  -Location $location
              
              
              # Create an App Service plan in Free tier.
              New-AzAppServicePlan -Name  $webappname -ResourceGroupName $resourceGroup -Location $location -Tier Free
              
              
              # Create a web app
              New-AzWebApp -Name $webappname -AppServicePlan $webappname -ResourceGroupName $resourceGroup -Location $location
            azurePowerShellVersion: 'LatestVersion'
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'Azure Personal(3772de55-f369-4548-afb2-3811c07a435b)'
            ScriptType: 'InlineScript'
            Inline: |
              $app = Get-AzWebApp -ResourceGroupName $resourceGroup -Name $webappname
              Publish-AzWebApp -WebApp $app -ArchivePath '$(Build.ArtifactStagingDirectory)\aspnet-get-started.zip' -AsJob
            azurePowerShellVersion: 'LatestVersion'
        
